backend:
  name: github
  repo: filhosdaluz/intercessao  # Substitua com seu nome de usuário e repositório
  branch: main  # Ou "master", dependendo do seu repositório

media_folder: "images/uploads"  # Pasta onde as imagens serão armazenadas
public_folder: "/images/uploads"  # URL pública para as imagens

collections:
  - name: "posts"  # Nome da coleção
    label: "Postagens"
    folder: "content/posts"  # Pasta onde os arquivos Markdown são armazenados
    create: true  # Permite criar novos posts
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Data", name: "date", widget: "datetime" }
