backend:
  name: github
  repo: filhosdaluz/intercessão  # Substitua com seu nome de usuário no GitHub e o nome do seu repositório
  branch: main  # Ou "master", dependendo do seu repositório

media_folder: "images/uploads" # Pasta para armazenar imagens
public_folder: "/images/uploads" # Caminho público para acessar as imagens

collections:
  - name: "posts"  # Nome da coleção
    label: "Postagens"
    folder: "content/posts"  # Caminho onde os arquivos de conteúdo (Markdown) são armazenados
    create: true  # Permite criar novos posts
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Data", name: "date", widget: "datetime" }
